DROP DATABASE  `navidrone`;
CREATE DATABASE `navidrone`;

CREATE TABLE  `navidrone`.`UTILISATEUR` (
  `UTILISATEUR_ID` INT(10) NOT NULL AUTO_INCREMENT,
  `UTILISATEUR_NOM` VARCHAR(20) NOT NULL,
  `UTILISATEUR_PRENOM` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`UTILISATEUR_ID`) USING BTREE,
  INDEX `IDX_UTILISATEUR_ID` (`UTILISATEUR_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

INSERT INTO `navidrone`.`UTILISATEUR` (UTILISATEUR_NOM,UTILISATEUR_PRENOM) values ('TEST','BOB');
select * from `navidrone`.`UTILISATEUR`;